//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermerGoodsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodFeedBack
    {
        public int Id { get; set; }
        public string ClientUserName { get; set; }
        public int GoodId { get; set; }
        public string Info { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Good Good { get; set; }
    }
}
