//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FermerGoodsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderGoods = new HashSet<OrderGood>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime DateStart { get; set; }
        public string Address { get; set; }
        public string ContactPhone { get; set; }
        public double TotalPrice { get; set; }
        public Nullable<System.TimeSpan> DeliveryTime { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderGood> OrderGoods { get; set; }
    }
}
